version: 0.2

phases:
  install:
    runtime-versions:
       java: corretto17
    commands:
        - apt-get update -y
        - apt-get install -y maven
  pre_build:
    commands:
       - java -version
       - mvn -version 
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean package
  post_build:
    commands:
      - echo Build completed successfully
# artifacts:
#   files:
#     - target/order-service.jar
#   discard-paths: yes
