---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaapplication
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: samplejava
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: samplejava
    spec:
      containers:
      - name: sample-java-container
      - image: 896147.dkr.ecr.ap-south-1.amazonaws.com/test1:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: servicejavamodule
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app.kubernetes.io/name: samplejava